CREATE PROCEDURE `new_procedure` ()
BEGIN
	
    WITH recharge30 AS (
	SELECT CUSTOMERID AS CUSTOMERID, sum(RECHARGEAMOUNT) AS CUMULLATIVE30
	FROM recharges
	WHERE RECHARGEDATETIME >= CURDATE()-30
	GROUP BY CUSTOMERID),
		recharge90 AS (
	SELECT CUSTOMERID AS CUSTOMERID, sum(RECHARGEAMOUNT) AS CUMULLATIVE90
	FROM recharges
	WHERE RECHARGEDATETIME >= CURDATE()-90
	GROUP BY CUSTOMERID)
    

	UPDATE customers SET CUMULATIVE30DAYS = recharge30.cumulative30, CUMULATIVE90DAYS = recharge90.cumulative90
	WHERE CUSTOMERID = recharge30.customers
    AND CUSTOMERID = recharge90.customers;
    
END
